openapi: 3.1.0
info:
  title: mod-dlm API
  description: mod-dlm is an open source domain specific language to describe
    prefab construction elements. This project provides tools for defining
    entity models and automatically generating CRUD APIs, enabling suppliers to
    create and manage catalogs of their products easily.
  version: 1.0.10
  contact:
    name: Contact us
    url: https://mod.construction
    email: info@mod.construction
  license:
    name: MIT
    url: https://github.com/mod-construction/mod-dlm/blob/main/LICENSE
  x-logo:
    url: mod-dlm-logo.png
    backgroundColor: "#FFFFFF"
    altText: mod-dlm logo
servers:
  - url: http://localhost:8080
    description: The dev server.
  - url: https://mod.construction
    description: The production server.
security:
  - apiKey: []
    bearer: []
paths:
  /element:
    get:
      operationId: getElement
      summary: Get an element
      description: Gets an element from the database.
      parameters:
        - in: path
          name: id
          description: A unique identifier for an element
          schema:
            $ref: "#/components/schemas/ElementId"
          required: true
      responses:
        "200":
          description: The element was retrieved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PrefabElement"
        "400":
          description: Bad request.
        "401":
          description: Authorization information is missing or invalid.
        "404":
          description: An element with the specified ID was not found.
    post:
      operationId: createElement
      summary: Create a new element
      description: Creates a new element in the database.
      requestBody:
        description: The element to create.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ElementCreate"
      responses:
        "201":
          description: The element was created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PrefabElement"
        "400":
          description: Bad request.
        "401":
          description: Authorization information is missing or invalid.
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY
      description: API key for programmatic access.
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: An embedded jason web token.
  schemas:
    ElementId:
      type: string
      format: uuid
      description: A unique identifier for an element
      example: 4dd643ff-7ec7-4666-9c88-50b7d3da34e4
    PrefabElement:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/ElementId"
        name:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        boundingBox:
          type: object
          properties:
            width:
              type: number
              exclusiveMinimum: 0
            height:
              type: number
              exclusiveMinimum: 0
            depth:
              type: number
              exclusiveMinimum: 0
          required:
            - width
            - height
            - depth
          description: The bounding box of an element in millimeters.
        images:
          type: array
          items:
            type: string
          minItems: 1
        productCategory:
          $ref: "#/components/schemas/ProductCategory"
        material:
          type: object
          properties:
            finishMaterial:
              type: string
              enum:
                - Timber
                - Steel
                - Concrete
                - Hybrid
                - Other
            structuralMaterial:
              type: string
              enum:
                - Timber
                - Steel
                - Concrete
                - Hybrid
                - Other
          required:
            - finishMaterial
            - structuralMaterial
        dimensional:
          type: object
          properties:
            width:
              type: object
              properties:
                min:
                  type: number
                max:
                  type: number
              required:
                - min
                - max
            height:
              type: object
              properties:
                min:
                  type: number
                max:
                  type: number
              required:
                - min
                - max
            length:
              type: object
              properties:
                min:
                  type: number
                max:
                  type: number
              required:
                - min
                - max
          required:
            - width
            - height
            - length
        structuralProperties:
          type: object
          properties:
            loadBearingCapacity:
              type: object
              properties:
                maximumLoad:
                  type: number
                unit:
                  type: string
                  enum:
                    - N
                    - kN
                    - lbf
                    - kgf
                loadDistribution:
                  type: string
              required:
                - maximumLoad
                - unit
                - loadDistribution
            seismicResistance:
              type: string
              enum:
                - Zone 1
                - Zone 2
                - Zone 3
                - Zone 4
            windLoadResistance:
              type: string
              enum:
                - Class A
                - Class B
                - Class C
                - Class D
        performance:
          type: object
          properties:
            resistanceToFireClassification:
              type: string
              enum:
                - A1
                - A2
                - B
                - C
                - D
                - E
                - F
                - 1-hour
                - 2-hour
                - 3-hour
                - 4-hour
            thermalTransmittance:
              type: number
              minimum: 0
              maximum: 2
            acousticProperties:
              type: object
              properties:
                soundInsulationRating:
                  type: string
                acousticPerformance:
                  type: string
              required:
                - soundInsulationRating
                - acousticPerformance
          required:
            - resistanceToFireClassification
            - thermalTransmittance
        sustainability:
          type: object
          properties:
            countryOfManufacturing:
              type: string
            classification:
              type: string
              enum:
                - A+
                - A
                - B
                - C
                - D
            VOCEmissions:
              type: string
              enum:
                - None
                - Low
                - Medium
                - High
            recyclability:
              type: string
              enum:
                - 0%
                - 25%
                - 50%
                - 75%
                - 100%
            energyEfficiency:
              type: string
              enum:
                - R-1
                - R-2
                - R-5
                - Energy Star
                - LEED Certified
                - LEED Silver
                - LEED Gold
                - LEED Platinum
          required:
            - countryOfManufacturing
            - classification
        documentationAndCompliance:
          type: object
          properties:
            technicalSpecifications:
              type: string
            certifications:
              type: object
              properties:
                certificationTypes:
                  type: array
                  items:
                    type: string
                regulatoryApprovals:
                  type: array
                  items:
                    type: string
              required:
                - certificationTypes
                - regulatoryApprovals
          required:
            - technicalSpecifications
            - certifications
        installationAndConnectivity:
          type: object
          properties:
            connectionType:
              type: string
              enum:
                - Bolt-on
                - Welded
                - Clip-on
                - Adhesive
                - Mortar
            installationTime:
              type: string
            compatibility:
              type: string
              enum:
                - Steel Frame
                - Wood Frame
                - Concrete Structure
                - Brickwork
                - Modular Systems
                - Glass Facades
                - Composite Materials
        lifecycleAndMaintenance:
          type: object
          properties:
            expectedLifespan:
              type: string
            maintenanceRequirements:
              type: string
            warranty:
              type: string
        aestheticAndCustomizationOptions:
          type: object
          properties:
            colorOptions:
              type: array
              items:
                type: string
            texture:
              type: string
            modularAdaptability:
              type: string
        economicFactors:
          type: object
          properties:
            costPerUnit:
              type: number
            manufacturingLeadTime:
              type: string
      required:
        - id
        - name
        - description
        - boundingBox
        - images
        - productCategory
        - material
        - dimensional
      description: Prefab Element
    ProductCategory:
      type: object
      properties:
        category:
          type: string
          enum:
            - Boarding
            - Solid Wall Panels
            - Closed Wall Panels
            - Twinwall
            - Open Wall Panels
            - Structural Insulated Panels (SIPs)
            - Insulated Concrete Panels
            - Prefabricated Balcony
            - Pod
            - Whole Building System
            - Structural Frame
            - Facade System
            - Hollowcore Floor
            - Concrete Lattice Floor
            - Floor Cassettes
            - Solid Floor Panels
            - Volumetric module
            - Prefabricated Plant
            - Roof Panel
            - Roof Truss
            - Prefabricated Stairs
        buildingSystem:
          type: string
          enum:
            - Wall
            - Balcony
            - Pod
            - Frame
            - Facade
            - Floors
            - Modules
            - Plants
            - Roofs
            - Stairs
      required:
        - category
        - buildingSystem
      description: Product Category
      example:
        category: Solid Wall Panels
        buildingSystem: Wall
    ElementCreate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        boundingBox:
          type: object
          properties:
            width:
              type: number
              exclusiveMinimum: 0
            height:
              type: number
              exclusiveMinimum: 0
            depth:
              type: number
              exclusiveMinimum: 0
          required:
            - width
            - height
            - depth
          description: The bounding box of an element in millimeters.
        images:
          type: array
          items:
            type: string
          minItems: 1
        productCategory:
          $ref: "#/components/schemas/ProductCategory"
        material:
          type: object
          properties:
            finishMaterial:
              type: string
              enum:
                - Timber
                - Steel
                - Concrete
                - Hybrid
                - Other
            structuralMaterial:
              type: string
              enum:
                - Timber
                - Steel
                - Concrete
                - Hybrid
                - Other
          required:
            - finishMaterial
            - structuralMaterial
        dimensional:
          type: object
          properties:
            width:
              type: object
              properties:
                min:
                  type: number
                max:
                  type: number
              required:
                - min
                - max
            height:
              type: object
              properties:
                min:
                  type: number
                max:
                  type: number
              required:
                - min
                - max
            length:
              type: object
              properties:
                min:
                  type: number
                max:
                  type: number
              required:
                - min
                - max
          required:
            - width
            - height
            - length
        structuralProperties:
          type: object
          properties:
            loadBearingCapacity:
              type: object
              properties:
                maximumLoad:
                  type: number
                unit:
                  type: string
                  enum:
                    - N
                    - kN
                    - lbf
                    - kgf
                loadDistribution:
                  type: string
              required:
                - maximumLoad
                - unit
                - loadDistribution
            seismicResistance:
              type: string
              enum:
                - Zone 1
                - Zone 2
                - Zone 3
                - Zone 4
            windLoadResistance:
              type: string
              enum:
                - Class A
                - Class B
                - Class C
                - Class D
        performance:
          type: object
          properties:
            resistanceToFireClassification:
              type: string
              enum:
                - A1
                - A2
                - B
                - C
                - D
                - E
                - F
                - 1-hour
                - 2-hour
                - 3-hour
                - 4-hour
            thermalTransmittance:
              type: number
              minimum: 0
              maximum: 2
            acousticProperties:
              type: object
              properties:
                soundInsulationRating:
                  type: string
                acousticPerformance:
                  type: string
              required:
                - soundInsulationRating
                - acousticPerformance
          required:
            - resistanceToFireClassification
            - thermalTransmittance
        sustainability:
          type: object
          properties:
            countryOfManufacturing:
              type: string
            classification:
              type: string
              enum:
                - A+
                - A
                - B
                - C
                - D
            VOCEmissions:
              type: string
              enum:
                - None
                - Low
                - Medium
                - High
            recyclability:
              type: string
              enum:
                - 0%
                - 25%
                - 50%
                - 75%
                - 100%
            energyEfficiency:
              type: string
              enum:
                - R-1
                - R-2
                - R-5
                - Energy Star
                - LEED Certified
                - LEED Silver
                - LEED Gold
                - LEED Platinum
          required:
            - countryOfManufacturing
            - classification
        documentationAndCompliance:
          type: object
          properties:
            technicalSpecifications:
              type: string
            certifications:
              type: object
              properties:
                certificationTypes:
                  type: array
                  items:
                    type: string
                regulatoryApprovals:
                  type: array
                  items:
                    type: string
              required:
                - certificationTypes
                - regulatoryApprovals
          required:
            - technicalSpecifications
            - certifications
        installationAndConnectivity:
          type: object
          properties:
            connectionType:
              type: string
              enum:
                - Bolt-on
                - Welded
                - Clip-on
                - Adhesive
                - Mortar
            installationTime:
              type: string
            compatibility:
              type: string
              enum:
                - Steel Frame
                - Wood Frame
                - Concrete Structure
                - Brickwork
                - Modular Systems
                - Glass Facades
                - Composite Materials
        lifecycleAndMaintenance:
          type: object
          properties:
            expectedLifespan:
              type: string
            maintenanceRequirements:
              type: string
            warranty:
              type: string
        aestheticAndCustomizationOptions:
          type: object
          properties:
            colorOptions:
              type: array
              items:
                type: string
            texture:
              type: string
            modularAdaptability:
              type: string
        economicFactors:
          type: object
          properties:
            costPerUnit:
              type: number
            manufacturingLeadTime:
              type: string
      required:
        - name
        - description
        - boundingBox
        - images
        - productCategory
        - material
        - dimensional
      description: An element to create.
