export export enum ProductCategory {
    Boarding = 'Boarding',
    SolidWallPanels = 'Solid Wall Panels',
    ClosedWallPanels = 'Closed Wall Panels',
    Twinwall = 'Twinwall',
    OpenWallPanels = 'Open Wall Panels',
    SIPs = 'Structural Insulated Panels (SIPs)',
    InsulatedConcretePanels = 'Insulated Concrete Panels',
    PrefabricatedBalcony = 'Prefabricated Balcony',
    Pod = 'Pod',
    WholeBuildingSystem = 'Whole Building System',
    StructuralFrame = 'Structural Frame',
    FacadeSystem = 'Facade System',
    HollowcoreFloor = 'Hollowcore Floor',
    ConcreteLatticeFloor = 'Concrete Lattice Floor',
    FloorCassettes = 'Floor Cassettes',
    SolidFloorPanels = 'Solid Floor Panels',
    VolumetricModule = 'Volumetric module',
    PrefabricatedPlant = 'Prefabricated Plant',
    RoofPanel = 'Roof Panel',
    RoofTruss = 'Roof Truss',
    PrefabricatedStairs = 'Prefabricated Stairs'
}