blank_issues_enabled: false
contact_links:
  - name: 🤔 Help & Questions
    url: https://discord.com/channels/1037357119495733278/1229871904039637116
    about: Ask general support or usage questions in the opensource.construction Community forums
