packageName: mod_dlm_server
templateDir: generator-configs/template
files:
  SECURITY.md: {}
  LICENSE: {}
  CODE_OF_CONDUCT.md: {}
  CONTRIBUTING.md: {}
  fastapi/mod-dlm-fastapi-server.png:
    destinationFilename: mod-dlm-fastapi-server.png
    templateType: SupportingFiles
  fastapi/requirements.txt:
    destinationFilename: requirements.txt
    templateType: SupportingFiles
  fastapi/README-fastapi.mustache:
    destinationFilename: README.md
    templateType: SupportingFiles
  fastapi/setup_cfg.mustache:
    destinationFilename: setup.cfg
    templateType: SupportingFiles
