packageName: construction.mod.dlm
groupId: construction.mod
artifactId: dlm-server
apiPackage: construction.mod.dlm.api
modelPackage: construction.mod.dlm.model
configPackage: construction.mod.dlm.configuration
invokerPackage: construction.mod.dlm
library: spring-cloud
beanValidations: true
serviceImplementation: true
dateLibrary: java8
templateDir: generator-configs/template
files:
  SECURITY.md: {}
  LICENSE: {}
  CODE_OF_CONDUCT.md: {}
  CONTRIBUTING.md: {}
  spring/mod-dlm-spring-server.png:
    destinationFilename: mod-dlm-spring-server.png
    templateType: SupportingFiles
  spring/README-spring.mustache:
    destinationFilename: README.md
    templateType: SupportingFiles