name: Generate API Servers

on:
  push:
    branches:
      - main
  release:
    types: [ created ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate Spring Server
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: spring
          openapi-url: https://mod-construction.github.io/mod-dlm/openapi.yaml
          config-file: generator-configs/spring-generator-config.yml
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-files: '/github/workspace/spring-client'
          destination-username: 'mod-construction'
          destination-repository: 'mod-dlm-server-spring'
          commit-email: 'moradi.yashar@gmail.com'

